version: "{build}"

clone_depth: 10

configuration:
  - Release

platform: Any CPU

before_build:
  - nuget restore

build_script:
  - msbuild "GitCredentialManager.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /consoleloggerparameters:Verbosity=normal /nodeReuse:false /target:"Build" /property:Configuration="%configuration%";Platform="%platform%"

cache:
  - packages -> **\packages.config

matrix:
  fast_finish: true
