version: "{build}"

image: Visual Studio 2017

clone_depth: 10

configuration:
  - Release

platform: Any CPU

before_build:
  - nuget restore

build_script:
  - msbuild "GitCredentialManager.sln" /bl:GitCredentialManager.binlog /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /consoleloggerparameters:Verbosity=normal /m /nodeReuse:false /target:"Build" /property:Configuration="%configuration%";Platform="%platform%"

cache:
  - packages -> **\packages.config

matrix:
  fast_finish: true

artifacts:
  - path: GitCredentialManager.binlog
    name: MSBuild Log

on_failure:
  - appveyor PushArtifact GitCredentialManager.binlog
